name: Another LAO Test
favicon: null
layout_spectrum: 0.5942013303283602
typography_spectrum: 0.8573051332496107
title: Another LAO test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6050013517960906
  lightness: 0.32596815610304475
  saturation: 0.40383889991790056
  rhythmicContrast: 0.16414125612936914
purpose: []
